name: teeth_selector
description: A simple dental chart showing teeth that can be selected/unselected like a set of checkboxes.
version: 0.0.1
homepage: https://github.com/alselawi/teeth_selector

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'This screenshot shows an example of teeth selector.'
    path: screenshots/screenshot.png

topics:
  - ui
  - teeth
  - tooth
  - dental
  - dental-chart

flutter:
